### ISSUE TITLE
Move PORT to ENV

### ISSUE THREAD

**Issue by LokeYourC3PH** [sirjmann92/nicotineplus-proper#1]
Hello there! I want to host Nicotine+ on my UGREEN NAS, and I already host a couple of Docker containers on my NAS. However, nicotineplus-proper seems to set the port at which the WebUI is exposed at in a static manner (ref: https://github.com/sirjmann92/nicotineplus-proper/blob/510a96e8d50c1ad23cf47e6038fa4677e23787f2/Dockerfile#L20)

Would you be able to let people adjust this via moving this into the ENV section instead?

Thank you!

**Comment by LokeYourC3PH** [comment]
Another bug I noticed btw, is that even if the volume is set, the container still tries to read (and fails) from the local /home/ directory:

nicotineplus-proper (docker-compose.yml):
```
   volumes:
     - /volume1/Music:/downloads
     - /volume1/Music:/shared
     - /volume2/docker/nicotineplus/config:/config # Optional: Save your config persistently
     - /volume2/docker/nicotineplus/config/data:/data # Optional: Store your logs, database, and history
```

Logs output:
```
[06/17/24 00:03:55] The current nicotine UID/GID is:

[06/17/24 00:03:55] uid=1000(nicotine) gid=1000(nicotine) groups=1000(nicotine)

[06/17/24 00:03:55] Starting NGINX server...

[06/17/24 00:03:55] Starting Broadway daemon...

[06/17/24 00:03:55] Configuration file not found

[06/17/24 00:03:55] Importing default configuration...

cp: cannot create regular file '/home/nicotine/.config/nicotine/config': Permission denied

Failed to import default configuration. Exiting...
```

**Comment by sirjmann92** [comment]
I'll have to think about how to go about allowing the port to be changed. The port is also used in an nginx config for tab name and favicon injection. I'll have to look into using variables and pushing data to this file at run time.

Regarding your permissions issue, please make sure you create the directories with a user that has the same permissions you're telling the container to use, BEFORE you start the container. Both the /config and /data directories should exist already at run time.

**Comment by LokeYourC3PH** [comment]
> 
> Regarding your permissions issue, please make sure you create the directories with a user that has the same permissions you're telling the container to use, BEFORE you start the container. Both the /config and /data directories should exist already at run time.

Normally containers handle this themselves, so it's kind of weird that nicotineplus-proper doesn't create its directories on its own, but I will try doing so.

**Comment by sirjmann92** [comment]
Think of the application as a user. As such, the application needs to have permission to do what you're asking it to do (read, write). If you want the application to run as root, then yes, 0:0 would work. If you use sudo commands to run your docker run time scripts, ("sudo docker run" or "sudo docker compose up -d") then you wouldn't have any permission issues, however, now the application is running as root, which is a security risk.

When you define the user, and if the directories don't exist before container creation, then DOCKER will create the directories (NOT the image). And if you run docker as sudo (root), then now your directories will have root privileges but your application will be running as a user (1000:1000). The directions clearly indicate to create the directories before you start the container for this reason. 

There are several ways around this, and you're welcome to use them (such as using chown to take ownership) but those are outside of the scope of this project, and I cannot provide general Linux/permissions support.

If we can keep this issue to the original request of allowing for WebUI port mapping, that would be great. I'll take a look at this when I have some time.

**Comment by sirjmann92** [comment]
@LokeYourC3PH , This is completed. Please pull a new "latest" image and give it a go! Directions are updated to include "WEB_UI_PORT" environment variable. I've tested with both standalone and VPN container attachment.

Let me know if you run into any issues.

**Comment by sirjmann92** [comment]
Closing as completed
