### ISSUE TITLE
Cannot open Url https://www.slsknet.org/qtlogin.php?username=redacted: No known url provider available.

### ISSUE THREAD

**Issue by Rom0067** [sirjmann92/nicotineplus-proper#11]
Hello and thanks for this container. It is awesome! I am brand new to slsk and am getting the title error when I try to open any links in the gui.  I have the container running on a vps and am able to upload/download with no issues at all.  I think this error might refer to url handlers in the preferences but I don't know how to fix it.  Any help would be greatly appreciated.  I have attached an image of what I think may be the issue in hopes it will help with a resolution.  Thanks you!

![image_2024-11-25_202530421](https://github.com/user-attachments/assets/d3cd26b2-58a2-4d41-9d3b-122672b6d40c)

**Comment by hboetes** [comment]
https://github.com/nicotine-plus/nicotine-plus/discussions/3012

**Comment by Rom0067** [comment]
> Hello, and thank you for the issue and I'm glad you're enjoying the project!
> 
> I'm aware of this and, unfortunately, this is undesired but expected behavior. The container does not have a browser or URI/URL handlers or any other graphical applications installed, nor does it have awareness of the applications installed on the host machine. This renders the URL Handlers menu useless.
> 
> I've spoken to the developers of N+ about this in the past. I'm hoping they will make some additional changes for the Broadway implementation of the application to use static URLs, conditionally, so that the experience is smoother for users of this project (I think I still owe them a feature request for this). Until then, there's nothing I can do without a lot of effort and a massive impact to performance.
> 
> Please remember that this is a desktop application, converted to HTML5 and displayed in a browser using the Broadway backend of GTK, this is not a native web application.
> 
> For more information on the method, see here: https://docs.gtk.org/gtk3/broadway.html

Thank you for reaching out.  Its all good.  This container as is, for me, works pretty damn well!  Thank you for making it and I look forward to future improvements!
