### ISSUE TITLE
Any reason not to use GT4/Broadway 2.0 ?

### ISSUE THREAD

**Issue by vctls** [sirjmann92/nicotineplus-proper#13]
As far as I know, Nicotine+ is already using GTK4, and from the brief tests I did on my machine, performance seemed better with Broadway 2.0.  
But maybe there are some issues I didn't see.

**Comment by sirjmann92** [comment]
I have both versions, GTK3 is much more stable and less quirky (like opening windows in the center of the screen instead of top left, menu items requiring moving off and back before clicking, etc.) But you're welcome to use the gtk4 tag if you wish, both have the same features available.

**Comment by vctls** [comment]
OK, I'll try that. For some reason, I'm having issues with GTK3 when running Broadway directly on the host, but I'm hoping it will work better in a container.

**Comment by sirjmann92** [comment]
You can see all of the versions I have available at https://hub.docker.com/repository/docker/sirjmann92/nicotineplus-proper/tags - But the main versions are
- "latest" (latest stable with an Ubuntu base)
- "test" (latest dev branch with Ubuntu base)
- "gtk4" (gtk4 variant with Ubuntu base)
- "alpine" (latest stable with Alpine base)
- "alpine-test" (latest dev with Alpine base)

There are some other ones that are old or used for testing. Just stick with any of those and you'll be fine. If you really care about stability stick with "latest" and "alpine".

**Comment by slook** [comment]
> GTK3 is much more stable and less quirky (like opening windows in the center of the screen instead of top left, menu items requiring moving off and back before clicking, etc.) But you're welcome to use the gtk4 tag if you wish

If there are bugs then they will need to be identified and reported upstream (to N+ and/or GTK), because support for GTK 3 will cease eventually.

To enable proper investigation, it could be helpful to see if such bugs are reproducible in a `gtk-demo` app, see:
https://docs.gtk.org/gtk4/tools.html
https://gitlab.gnome.org/GNOME/gtk/-/tree/main/demos
https://github.com/GNOME/gtk/tree/main/demos

**Comment by vctls** [comment]
The main issue with GTK4 seems to be that menus and modals sometimes don't register clicks And it seems to happen more often when the modal has been moved first, but I can't say for sure.

But for some reason, Broadway with GTK3 consumes _a lot_ more CPU. And as stated before, it feels overall less performant. So I think I'll stick with GTK4 despite the few glitches.

**Comment by mathiascode** [comment]
I've worked around the click-related issues in https://github.com/nicotine-plus/nicotine-plus/commit/8aae8a1cadb11ea9a42f39decd216849ec53db53. Once the images are updated, let me know if you still run into similar issues in the GTK 4 version.

@vctls What browser are you using? I'm curious if scrolling large lists in the GTK 4 version feels sluggish on your end or not. Do you notice any difference if you add `?datauri` to the end of the URL (e.g. `http://localhost:8080/?datauri`).

**Comment by sirjmann92** [comment]
@mathiascode - I've updated my GTK4 image to latest UNSTABLE and switched to isolated mode. Some of the menu issues still persist. When you navigate to help, then try to navigate back while your mouse pointer is still over the menu, then the mouse pointer stops tracking and you have to move the mouse pointer off the menu and back in order for it to track again.

?daturi doesn't seem to make a difference for me with Brave. It still gets "stuck" when you grab the scrollbar and scroll long distances. If you use your mouse wheel it's less noticeable.

**Comment by vctls** [comment]
Just pulled the latest GTK4 image. I had the click issue once, but cannot reproduce it.
Interface is not super reactive, but I'm not on my local network and the service is behind a reverse proxy with authentication, so I'm not expecting crazy performance. I didn't see any major slowdown even when browsing large libraries. CPU usage stays low.
If there are any differences using `?datauri`, they are not noticeable enough for me to say for sure.  
I'd need actual automated tests to be sure, at this point.

**Comment by AverageHoarder** [comment]
I think I've encountered one of these GT4 issues (I'm using the sirjmann92/nicotineplus-proper:gtk4 image). For me it's mainly the wishlist that does not respond until I start typing into the search field and close and re-open it multiple times. After that the window reacts normally until I close it, at which point it's frozen again until I repeat the procedure.
I also noticed that settings windows often do not react until I close and re-open them a couple times, but not as bad (and consistent) as the wishlist.
I created a gif to show what I mean.
![wishlist gtk4](https://github.com/user-attachments/assets/9c4bf2ba-c59d-4464-8a81-be942ae79e28)

**Comment by sirjmann92** [comment]
@AverageHoarder , thanks for reporting this! Does this also happen on the standalone version of N+, or just the container version? Are you using a reverse proxy in your setup? 

- If this is also happening on the standalone version of N+, on any platform, please open an issue at the N+ GitHub page, here: https://github.com/nicotine-plus/nicotine-plus/issues
- If this is only happening on the container version, would you mind opening a new issue with some more details about your setup?

Thanks

**Comment by sirjmann92** [comment]
@AverageHoarder , the N+ developers made some fixes in the latest dev branch of N+ that might (should?) address this. I've updated my test image with that version. Can you please try the "gtk4-test" tag and let me know if your results are the same before you bother opening new issues?

**Comment by AverageHoarder** [comment]
> Can you please try the "gtk4-test" tag and let me know if your results are the same before you bother opening new issues?

Done that. The wishlist issues are gone with the test image.
Thanks!

**Comment by sirjmann92** [comment]
@AverageHoarder , thank you for confirmation. When 3.3.8 is released, you can move back to the "gtk" tag and it will have the changes.
