### ISSUE TITLE
UMASK envvar

### ISSUE THREAD

**Issue by wolfchimneyrock** [sirjmann92/nicotineplus-proper#14]
please add support for setting a umask for permissions of downloaded files

**Comment by sirjmann92** [comment]
@wolfchimneyrock - Can you help me with your use case? I've seen other containers do this, but I have to admin I don't really understand why, if your user permissions are set properly and you setup my N+ container with those user permissions, aren't your files created with the correct permissions? Is this a multi-user environment where you can't (or don't want to) run the container/application with the same UID/GID as the directory owner?

**Comment by wolfchimneyrock** [comment]
yes, its a multi-user environment, the container has a dedicated UID and shared GID with users who browse the share via samba and want to be able to individually modify / move the files - hence being able to set a umask of 002 allows other UID of the same GID to have write access to the files

**Comment by slook** [comment]
Something like this was recently added in slskd. These discussions are interesting and could be relevant, see:

https://github.com/slskd/slskd/issues/49
https://github.com/slskd/slskd/issues/1028

https://github.com/slskd/slskd/pull/1128

https://docs.linuxserver.io/general/understanding-puid-and-pgid/

If it needs to be implemented in N+ itself to support this use case, then make a feature request or PR there. The code which moves the finished file from the Incomplete -> Complete folder is [here](https://github.com/nicotine-plus/nicotine-plus/blob/f5a7b32eaeee946df9c667dae49536ddde19734e/pynicotine/downloads.py#L424), which might be a good place to set the umask.

**Comment by wolfchimneyrock** [comment]
> Something like this was recently added in slskd. These discussions are interesting and could be relevant, see:
> 
> [slskd/slskd#49](https://github.com/slskd/slskd/issues/49) [slskd/slskd#1028](https://github.com/slskd/slskd/issues/1028)
> 
> [slskd/slskd#1128](https://github.com/slskd/slskd/pull/1128)
> 
> https://docs.linuxserver.io/general/understanding-puid-and-pgid/
> 
> If it needs to be implemented in N+ itself to support this use case, then make a feature request or PR there. The code which moves the finished file from the Incomplete -> Complete folder is [here](https://github.com/nicotine-plus/nicotine-plus/blob/f5a7b32eaeee946df9c667dae49536ddde19734e/pynicotine/downloads.py#L424), which might be a good place to set the umask, such as with `os.chmod()`.

making the change in nicotine itself won't work, since the default linux umask is 022 even if the application sets the group write flag, it will be ignored, it has to be at the os i.e. docker container level

**Comment by sirjmann92** [comment]
This sounds legit. I'll work on it today but I'll need your help to test @wolfchimneyrock , since I don't exactly have the right environment.

**Comment by wolfchimneyrock** [comment]
> This sounds legit. I'll work on it today but I'll need your help to test @wolfchimneyrock , since I don't exactly have the right environment.

ok

**Comment by wolfchimneyrock** [comment]
apparently, the linuxserver images already have UMASK implemented, alternatively you could switch the base image from ubuntu to something like `ghcr.io/linuxserver/baseimage-alpine` and get UMASK for free

https://discourse.linuxserver.io/t/how-to-set-umask-umask-vs-umask-set/1825

**Comment by sirjmann92** [comment]
I've already implemented it in my test image. I do have an Alpine and Alpine base images but Alpine is extremely finicky to work with, it's not "standard" at all. So I'll probably abandon it.

Can you test with my "test" image? I just uploaded it...

This image is currently based on N+ 3.3.8dev1, Ubuntu 24.04, and it adds time zone (TZ), locale (LANG), and UMASK (UMASK) support.

Let me know if it doesn't work.

**Comment by wolfchimneyrock** [comment]
it didn't work, I see the log "Setting UMASK to ..." but I think its getting lost between init.sh and launch.sh since su invokes a new shell - you might need to pass it into launch.sh and run umask there, or you might have to write to the nicotine user's profile to set the umask.

i don't know what dbus-launch does, that also might drop the umask setting

**Comment by sirjmann92** [comment]
@wolfchimneyrock 

I moved the umask logic into launch.sh but I have no idea how it's going to behave. It doesn't seem to have a negative effect when umask is NOT set, but you'll have to let me know how it works when it is.

If you can explain a relatively painless way to test it maybe I can test it a bit as I make changes.

I also recently discovered that dbus-x11 (the package and the command) are no longer needed, so they've been removed. Let me know if you notice any oddities. 

Go ahead and pull a new image and give it a spin.

Thanks

**Comment by wolfchimneyrock** [comment]
ok it worked this time! thanks!

btw I think you can remove the umask bit from init.sh and just keep it in launch.sh

**Comment by sirjmann92** [comment]
All images have been updated, files cleaned up, README updated, etc...

Let me know if you have any issues.
