### ISSUE TITLE
Cannot copy paste

### ISSUE THREAD

**Issue by minicoz** [sirjmann92/nicotineplus-proper#2]
Hey! Thanks for doing this. Its much smoother than the other solutions I have found.

My issue is that you cant copy past from the app to your browser. How could we implement that?

**Comment by sirjmann92** [comment]
The clipboard is disabled in upstream Broadway. Nothing I can do about this (I'm not a developer). It's a longstanding issue in GTK (years). See here: https://gitlab.gnome.org/GNOME/gtk/-/issues/2277 

If someone fixes/implements this in GTK, we can inherit the feature.
