### ISSUE TITLE
No profile pictures

### ISSUE THREAD

**Issue by mlnl221** [sirjmann92/nicotineplus-proper#3]
Another issue I found is that my profile picture wont load.

I get this error:

`Failed to load picture for user ....: Couldnt find foreign struct convert for 'cairo.Surface'` 

I couldn't copy paste this so I typed it out.

**Comment by sirjmann92** [comment]
I don't use profile pictures with N+ (didn't even know it was a thing). I doubt I can fix this myself, but I'll check with the N+ developers and see if there's anything that can be done without much fuss.

Thanks for reporting it. I'll leave it open until I learn more and report back.

**Comment by mathiascode** [comment]
Most likely missing the `python3-gi-cairo` dependency.

**Comment by sirjmann92** [comment]
Thanks @mathiascode - That seems to have fixed it. I've updated the Dockerfile and uploaded new images.

@minicoz - Please pull a new "latest" image, check again, and report back. I'm seeing the profile pictures now.
