### ISSUE TITLE
The docker compose example has the wrong image tag

### ISSUE THREAD

**Issue by unai-ndz** [sirjmann92/nicotineplus-proper#7]
Should be `:latest` instead of `:user`

**Comment by sirjmann92** [comment]
The docker run example was also incorrect. These instructions started when I first implemented user-based features, so I had a "user" build, which eventually ended up being the "latest" build, and I guess I overlooked updating that part of the instructions.

Thank you for catching this and letting me know. Both instances should be correct now.

Let me know if you find any other errors or issues.

**Comment by Byrnesdigital** [comment]
I noticed that as well.
